configs:
  params:
    server.insecure: true
server:
  service:
    type: "LoadBalancer"
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      selector:
        release: kube-prometheus-stack
controller:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      selector:
        release: kube-prometheus-stack
redis:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      selector:
        release: kube-prometheus-stack
repoServer:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      selector:
        release: kube-prometheus-stack
applicationSet:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      selector:
        release: kube-prometheus-stack
notifications:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      selector:
        release: kube-prometheus-stack