name: "Apply Terraform Composite Action"
description: "A composite action to apply terraform"
inputs:
  workspace:
    description: "Terraform Workspace"
    required: true
  plan_output:
    description: "Terraform Plan Output FileName"
    required: true
  working_directory:
    description: "Terraform Working Directory"
    required: true
  tf_api_token:
    description: "Terraform API Token"
    required: true
runs:
  using: "composite"
  steps:
    - name: Initialize Terraform
      uses: ./.github/actions/initialize_terraform_composite_action
      with:
        working_directory: ${{ inputs.working_directory }}
        tf_api_token: ${{ inputs.tf_api_token }}

    - name: Selecting Terraform Workspace
      id: workspace
      run: |
        cd ${{ inputs.working_directory }}
        terraform workspace select -or-create ${{ inputs.workspace }}
      shell: bash

    - name: Validating Terraform
      id: validate
      run: |
        cd ${{ inputs.working_directory }}
        terraform validate -no-color
      shell: bash

    - name: Planning Terraform
      id: plan
      run: |
        cd ${{ inputs.working_directory }}
        terraform plan -out=${{ inputs.plan_output }}
      shell: bash

    - name: Applying Terraform
      id: apply
      run: |
        cd ${{ inputs.working_directory }}
        terraform apply ${{ inputs.plan_output }}
      shell: bash