name: 'Create a Cluster'

on:
  push:
    branches:
      - 'master'
    paths:
      - '.env'
      
env:
  TF_CLOUD_ORGANIZATION: "infraheads"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"

jobs:
  creating_cluster:
    runs-on: self-hosted
    permissions:
      contents: read
      pull-requests: write
    defaults:
      run:
        working-directory: "terraform"
    steps:
    - uses: actions/checkout@v4
  
    - name: Passing env file values to GITHUB_ENV
      run: cat $GITHUB_WORKSPACE/.env >> $GITHUB_ENV 

    - uses: hashicorp/setup-terraform@v3
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
        terraform_version: 1.7.5

    - name: Configure Terraform Cache
      run: echo "TF_PLUGIN_CACHE_DIR=$HOME/.terraform.d/plugin-cache" >> "$GITHUB_ENV"

    - name: Initializing Terraform
      id: init
      run: terraform init -upgrade
      env:
        TF_WORKSPACE: "default-ws"

    - name: Selecting Terraform Workspace
      id: workspace
      run: |
        set +e
        terraform workspace new $CLUSTER_NAME
        tf_exitcode=$?
        set -e
        if [ $tf_exitcode -ne 0 ]; 
        then
          echo """
            Error: Cluster already exists.
            Message: There is already a cluster with the name '$CLUSTER_NAME'. The cluster name MUST BE unique.
            """
          exit 1
        fi
      
    - name: Validating Terraform
      id: validate
      run: terraform validate -no-color

    - name: Planning Terraform
      id: plan
      env:
        TF_LOG: TRACE
        TF_VAR_talos_version: "$TALOS_VERSION"
        TF_VAR_k8s_version: "$K8S_VERSION"
        TF_VAR_proxmox_ip: "$HOST_IP"
        TF_VAR_proxmox_token_id: "${{ secrets.PROXMOX_TOKEN_ID }}"
        TF_VAR_proxmox_token_secret: "${{ secrets.PROXMOX_TOKEN_SECRET }}"
        TF_VAR_cluster_name: "$CLUSTER_NAME"
        TF_VAR_controlplane_cores: "$CONTROLPLANE_CPU_CORES"
        TF_VAR_controlplane_memory: "$CONTROLPLANE_MEMORY"
        TF_VAR_controlplane_disk_size: "$CONTROLPLANE_DISK_SIZE"
        TF_VAR_worker_nodes_count: "$WORKER_NODES_COUNT"
        TF_VAR_worker_cores: "$WORKER_CPU_CORES"
        TF_VAR_worker_memory: "$WORKER_MEMORY"
        TF_VAR_worker_disk_size: "$WORKER_DISK_SIZE"
      run: terraform plan -out=tfplan

    - name: Applying Terraform
      id: apply
      env:
        TF_VAR_talos_version: "$TALOS_VERSION"
        TF_VAR_k8s_version: "$K8S_VERSION"
        TF_VAR_proxmox_ip: "$HOST_IP"
        TF_VAR_proxmox_token_id: "${{ secrets.PROXMOX_TOKEN_ID }}"
        TF_VAR_proxmox_token_secret: "${{ secrets.PROXMOX_TOKEN_SECRET }}"
        TF_VAR_cluster_name: "$CLUSTER_NAME"
        TF_VAR_controlplane_cores: "$CONTROLPLANE_CPU_CORES"
        TF_VAR_controlplane_memory: "$CONTROLPLANE_MEMORY"
        TF_VAR_controlplane_disk_size: "$CONTROLPLANE_DISK_SIZE"
        TF_VAR_worker_nodes_count: "$WORKER_NODES_COUNT"
        TF_VAR_worker_cores: "$WORKER_CPU_CORES"
        TF_VAR_worker_memory: "$WORKER_MEMORY"
        TF_VAR_worker_disk_size: "$WORKER_DISK_SIZE"
      run: |
        set +e
        terraform apply tfplan
        tf_exitcode=$?
        set -e
        if [ $tf_exitcode -ne 0 ];
        then
        echo """
          Error: Unable to create a Cluster.
          Message: This could be caused by a lack of resources in the server. Please review the server resources and try again.
          """
        exit 1
        fi

    - name: Generating kube-config
      uses: actions/upload-artifact@v4
      with:
        name: kube-config
        path: /tmp/kube-config
        compression-level: 0

    - name: Important Note
      run: echo "After the workflow is completed, the cluster gets ready within minutes, depending on the count of the worker nodes."
