name: 'Terraform Workflow'

on:
  workflow_dispatch:
    inputs:
      cluster_name:
        description: 'A unique Cluster name'
        required: true
        type: string

env:
  TF_CLOUD_ORGANIZATION: "infraheads"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"

jobs:
  terraform:
    runs-on: self-hosted
    permissions:
      contents: read
      pull-requests: write
    defaults:
      run:
        working-directory: "terraform"
    env:
      TF_VAR_proxmox_ip: "${{ secrets.PROXMOX_IP }}"
      TF_VAR_proxmox_token_id: "${{ secrets.PROXMOX_TOKEN_ID }}"
      TF_VAR_proxmox_token_secret: "${{ secrets.PROXMOX_TOKEN_SECRET }}"
      TF_VAR_cluster_name: "${{ inputs.cluster_name }}"
    steps:
    - uses: actions/checkout@v4

    - uses: hashicorp/setup-terraform@v2.0.3
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Init
      id: init
      run: terraform init
      env:
        TF_WORKSPACE: "default-ws"

    - name: Select workspace
      id: workspace
      run: terraform workspace new ${{ inputs.cluster_name }}

    - name: Validate
      id: validate
      run: terraform validate -no-color

    - name: Plan
      id: plan
      run: terraform plan -out=tfplan

    - name: Apply
      id: apply
      run: terraform apply tfplan